version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      # Checkout and restore dependency cache
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      # Download and cache dependencies
      - lockfile:
        - yarn global add greenkeeper-lockfile@1
      - run: greenkeeper-lockfile-update
      - run: yarn install --frozen-lockfile --non-interactive
      - run: greenkeeper-lockfile-upload
      - save_cache:
        key: v2-dependencies-{{ checksum "yarn.lock" }}
        paths:
          - "node_modules"

      # run tests and report the coverage
      - run: yarn test --coverage && yarn report-coverage
